server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
    username: root
    password: Huu@123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

vnpay:
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8888/api/v1/booking-service/payments/vnpay/callback
  ipn-url: https://b8d0aa68f709.ngrok-free.app/payments/vnpay/ipn
  tmn-code: RTZSTG9H
  secret-key: 2AZN4DDW57TB4Q4OS8A50XQTCR625BAT
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction

jwt:
  signerKey: "YlYC92Q2NQlTEWXqxCMLhICbRb561RUicb+iEvw2sOTdWNOUavYJorDKyItY+0awM6rExXLQuDDCImefylr/wYQdTksaXc0mpJkQcg87vys="
  #  valid-duration: 86400 # in second
  #  refreshable-duration: 259200 # in seconds
  valid-duration: 1
  refreshable-duration: 2


# Frontend URL
frontend:
  url: "http://localhost:3000"

cinema:
  service:
    url: http://localhost:8082

movie:
  service:
    url: http://localhost:8081

user:
  service:
    url: http://localhost:8080

recommendation:
  service:
    url: http://localhost:8084

