version: "3.9"

services:

  api-gateway:
    container_name: api-gateway
    image: api-gateway-image
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      SERVER_PORT: 8888
      APP_API_PREFIX: /api/v1
      APPLICATION_NAME: api-gateway
    networks:
      mynet:
        ipv4_address: 172.30.1.2
        aliases:
          - api.bookingticket.com
    depends_on:
      - user-service
      - movie-service
      - cinema-service
      - booking-service

  user-service:
    container_name: user-service
    image: user-service-image
    build:
      context: ./UserService
    ports:
      - "8080:8080"
    networks:
      mynet:
        ipv4_address: 172.30.1.10

  movie-service:
    container_name: movie-service
    image: movie-service-image
    build:
      context: ./MovieService
    ports:
      - "8081:8081"
    networks:
      mynet:
        ipv4_address: 172.30.1.11
    volumes:
      - ./uploads:/uploads

  cinema-service:
    container_name: cinema-service
    image: cinema-service-image
    build:
      context: ./CinemaService
    ports:
      - "8082:8082"
    networks:
      mynet:
        ipv4_address: 172.30.1.12

  booking-service:
    container_name: booking-service
    image: booking-service-image
    build:
      context: ./BookingService
    ports:
      - "8083:8083"
    networks:
      mynet:
        ipv4_address: 172.30.1.13

  recommendation-service:
    container_name: recommendation-service
    image: recommendation-service-image
    build:
      context: ./RecommendationService
    ports:
      - "8084:8084"
    networks:
      mynet:
        ipv4_address: 172.30.1.14

  mysql:
    container_name: mysql-db
    image: mysql:8.4.6
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      mynet:
        ipv4_address: 172.30.0.2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql_data:

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
