server:
  port: 8888
app:
  api-prefix: /api/v1
application:
  name: api-gateway
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: uploads
              uri: http://movie-service:8081
              predicates:
                - Path=${app.api-prefix}/uploads/**
              filters:
                - StripPrefix=2
            - id: user-service
              uri: http://user-service:8080
              predicates:
                - Path=${app.api-prefix}/user-service/**
              filters:
                - StripPrefix=3
            - id: movie-service
              uri: http://movie-service:8081
              predicates:
                - Path=${app.api-prefix}/movie-service/**
              filters:
                - StripPrefix=3
            - id: cinema-service
              uri: http://cinema-service:8082
              predicates:
                - Path=${app.api-prefix}/cinema-service/**
              filters:
                - StripPrefix=3
            - id: booking-service
              uri: http://booking-service:8083
              predicates:
                - Path=${app.api-prefix}/booking-service/**
              filters:
                - StripPrefix=3
            - id: recommendation-service
              uri: http://recommendation-service:8084
              predicates:
                - Path=${app.api-prefix}/recommendation-service/**
              filters:
                - StripPrefix=3