server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie-service
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

showtime:
  service:
    url: http://localhost:8082

cinema:
  service:
    url: http://localhost:8083
