server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://172.30.0.2:3306/moviedb
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: vuhuyhung17062002@gmail.com
    password: skwk jbiz qydz gqsc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  signerKey: "YlYC92Q2NQlTEWXqxCMLhICbRb561RUicb+iEvw2sOTdWNOUavYJorDKyItY+0awM6rExXLQuDDCImefylr/wYQdTksaXc0mpJkQcg87vys="
  #  valid-duration: 86400 # in second
  #  refreshable-duration: 259200 # in seconds
  valid-duration: 1
  refreshable-duration: 2

file:
  upload-dir: uploads/posters
  base-url: http://localhost:8081

cinema:
  service:
    url: http://172.30.1.12:8082

booking:
  service:
    url: http://172.30.1.13:8083

user:
  service:
    url: http://172.30.1.10:8080

recommendation:
  service:
    url: http://172.30.1.14:8084
